language: csharp
solution: PokemonGenerator.sln
install:
  - nuget install xunit.runner.console -ExcludeVersion -OutputDirectory packages
  - nuget install OpenCover -ExcludeVersion -OutputDirectory packages
  - nuget install coveralls.io -ExcludeVersion -OutputDirectory packages
script:
  - msbuild /t:Restore
  - msbuild /p:Configuration=Release PokemonGenerator.sln
  - mono ./packages/xunit.runner.console/tools/net452/xunit.console.exe ./tests/PokemonGenerator.Tests.Unit/bin/Release/net47/PokemonGenerator.Tests.Unit.dll
after_script: 
  - mono ./packages/OpenCover/tools/OpenCover.Console.exe -register:user -target:"./packages/xunit.runner.console/tools/net452/xunit.console.exe" -targetargs:"PokemonGenerator.Tests.Unit.dll -noshadow -nologo" -filter:"+[PokemonGenerator]* -[PokemonGenerator.Tests*]*" -output:"coverage.xml" -targetdir:"./tests/PokemonGenerator.Tests.Unit/bin/Release/net47" -skipautoprops -hideskipped:File -oldStyle -log:Off
  - mono ./packages/coveralls.io/tools/coveralls.net.exe --opencover coverage.xml -r $COVERALLS_REPO_TOKEN