version: 1.0.0.{build}-{branch}
skip_tags: true
image: Visual Studio 2017
clone_depth: 1

matrix:
  fast_finish: true

nuget:
  disable_publish_on_pr: true

environment:
  CODECOV_TOKEN:
    secure: NAzs6hcYUGTA2OH5CJwmRhMF0HR0fiYs9eSvB3nHpYAl7RqYOu3HtwyTkc4cDMZl

before_build:
- choco install opencover.portable
- choco install codecov

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- msbuild Installer\Installer.wixproj /t:Build /p:Configuration=Release /p:OutputPath=..\Artifacts\x64 /p:Platform=x64
- msbuild Installer\Installer.wixproj /t:Build /p:Configuration=Release /p:OutputPath=..\Artifacts\x86 /p:Platform=x86

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\tests\PokemonGenerator.Tests.Unit\bin\Release\net47\PokemonGenerator.Tests.Unit.dll -noshadow" -filter:"+[PokemonGenerator*]* -[PokemonGenerator.Tests*]*" -output:".\coverage.xml" -hideskipped:File -mergebyhash -skipautoprops -threshold:9999
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\tests\PokemonGenerator.Tests.Integration\bin\Release\net47\PokemonGenerator.Tests.Integration.dll -noshadow -parallel none" -filter:"+[PokemonGenerator*]* -[PokemonGenerator.Tests*]*" -output:".\coverage.xml" -hideskipped:File -mergebyhash -skipautoprops -threshold:9999
- codecov -f ".\coverage.xml"

artifacts:
  - path: Artifacts\x64
    name: Setup_x64
    type: zip
  - path: Artifacts\x86
    name: Setup_x86
    type: zip

deploy:
  release: Pokemon Generator v$(appveyor_build_version)
  description: 'Appveyor auto-generated release'
  provider: GitHub
  auth_token:
    secure: zQGJD6fs/xhZgf/3Rkagg765kNLqIsJ9ouxG/XUNknwalfz/jb8wp7+ZpTRzYhEp
  artifact: Setup_x64,Setup_x86
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
